### ISSUE TITLE
Last Two Tests Failed

### ISSUE THREAD

**Issue by Nathaniel-Han** [zcbenz/BPlusTree#1]
last two tests about _RemoveManyKeys_ failed. I think something goes wrong with `remove` routine.

I tried to debug myself, but it seems difficult to debug BplusTree. Got any advice? Thanks.

**Comment by fengh16** [comment]
> last two tests about _RemoveManyKeys_ failed. I think something goes wrong with `remove` routine.
> 
> I tried to debug myself, but it seems difficult to debug BplusTree. Got any advice? Thanks.

Have fixed in the PR #2
